from __future__ import annotations

import argparse
from pathlib import Path
from typing import Mapping


def build_summary_data(
    ns: argparse.Namespace,
    *,
    result: str,
    outdir: Path,
    connect_address: str,
    backend_room_key: str,
    backend_room_key_found: int,
    backend_launch_blocked: int,
    mapgen_players_override: int | None,
    mapgen_control_file: Path | None,
    expected_fail_tx_mode: int,
    runtime: Mapping[str, int | str],
    post: Mapping[str, int | str],
    optional: Mapping[str, int | str],
    mapgen_wait_reason: str,
    mapgen_reload_regen_ok: int,
    host_log: Path,
    pid_file: Path,
) -> dict[str, str | int | Path]:
    return {
        "RESULT": result,
        "OUTDIR": outdir,
        "DATADIR": ns.datadir if ns.datadir else "",
        "INSTANCES": ns.instances,
        "EXPECTED_PLAYERS": ns.expected_players,
        "AUTO_ENTER_DUNGEON": ns.auto_enter_dungeon,
        "AUTO_ENTER_DUNGEON_DELAY_SECS": ns.auto_enter_dungeon_delay,
        "AUTO_ENTER_DUNGEON_REPEATS": ns.auto_enter_dungeon_repeats,
        "CONNECT_ADDRESS": connect_address,
        "NETWORK_BACKEND": ns.network_backend,
        "BACKEND_ROOM_KEY": backend_room_key,
        "BACKEND_ROOM_KEY_FOUND": backend_room_key_found,
        "BACKEND_LAUNCH_BLOCKED": backend_launch_blocked,
        "FORCE_CHUNK": ns.force_chunk,
        "CHUNK_PAYLOAD_MAX": ns.chunk_payload_max,
        "MAPGEN_PLAYERS_OVERRIDE": mapgen_players_override if mapgen_players_override is not None else "",
        "MAPGEN_CONTROL_FILE": mapgen_control_file if mapgen_control_file is not None else "",
        "MAPGEN_RELOAD_SAME_LEVEL": ns.mapgen_reload_same_level,
        "MAPGEN_RELOAD_SEED_BASE": ns.mapgen_reload_seed_base,
        "START_FLOOR": ns.start_floor,
        "HELO_CHUNK_TX_MODE": ns.helo_chunk_tx_mode,
        "STRICT_ADVERSARIAL": ns.strict_adversarial,
        "REQUIRE_TXMODE_LOG": ns.require_txmode_log,
        "EXPECTED_FAIL_TX_MODE": expected_fail_tx_mode,
        "HOST_CHUNK_LINES": runtime["host_chunk_lines"],
        "CLIENT_REASSEMBLED_LINES": runtime["client_reassembled_lines"],
        "PER_CLIENT_REASSEMBLY_COUNTS": runtime["per_client_reassembly_counts"],
        "CHUNK_RESET_LINES": runtime["chunk_reset_lines"],
        "CHUNK_RESET_REASON_COUNTS": post["CHUNK_RESET_REASON_COUNTS"],
        "TX_MODE_APPLIED": runtime["tx_mode_applied"],
        "TX_MODE_LOG_LINES": runtime["tx_mode_log_lines"],
        "TX_MODE_PACKET_PLAN_OK": runtime["tx_mode_packet_plan_ok"],
        "EXPECTED_CHUNK_LINES": ns.instances - 1 if ns.instances > 1 else 0,
        "EXPECTED_REASSEMBLED_LINES": ns.instances - 1 if ns.instances > 1 else 0,
        "HELO_PLAYER_SLOTS": post["HELO_PLAYER_SLOTS"],
        "HELO_MISSING_PLAYER_SLOTS": post["HELO_MISSING_PLAYER_SLOTS"],
        "HELO_PLAYER_SLOT_COVERAGE_OK": post["HELO_PLAYER_SLOT_COVERAGE_OK"],
        "MAPGEN_FOUND": post["MAPGEN_FOUND"],
        "MAPGEN_COUNT": post["MAPGEN_COUNT"],
        "MAPGEN_SAMPLES_REQUESTED": ns.mapgen_samples,
        "MAPGEN_WAIT_REASON": mapgen_wait_reason,
        "GAMESTART_FOUND": post["GAMESTART_FOUND"],
        "MAPGEN_ROOMS": post["MAPGEN_ROOMS"],
        "MAPGEN_MONSTERS": post["MAPGEN_MONSTERS"],
        "MAPGEN_GOLD": post["MAPGEN_GOLD"],
        "MAPGEN_ITEMS": post["MAPGEN_ITEMS"],
        "MAPGEN_DECORATIONS": post["MAPGEN_DECORATIONS"],
        "MAPGEN_DECOR_BLOCKING": post["MAPGEN_DECOR_BLOCKING"],
        "MAPGEN_DECOR_UTILITY": post["MAPGEN_DECOR_UTILITY"],
        "MAPGEN_DECOR_TRAPS": post["MAPGEN_DECOR_TRAPS"],
        "MAPGEN_DECOR_ECONOMY": post["MAPGEN_DECOR_ECONOMY"],
        "MAPGEN_FOOD_ITEMS": post["MAPGEN_FOOD_ITEMS"],
        "MAPGEN_FOOD_SERVINGS": post["MAPGEN_FOOD_SERVINGS"],
        "MAPGEN_GOLD_BAGS": post["MAPGEN_GOLD_BAGS"],
        "MAPGEN_GOLD_AMOUNT": post["MAPGEN_GOLD_AMOUNT"],
        "MAPGEN_ITEM_STACKS": post["MAPGEN_ITEM_STACKS"],
        "MAPGEN_ITEM_UNITS": post["MAPGEN_ITEM_UNITS"],
        "MAPGEN_LEVEL": post["MAPGEN_LEVEL"],
        "MAPGEN_SECRET": post["MAPGEN_SECRET"],
        "MAPGEN_SEED": post["MAPGEN_SEED"],
        "MAPGEN_RELOAD_TRANSITION_LINES": post["MAPGEN_RELOAD_TRANSITION_LINES"],
        "MAPGEN_RELOAD_TRANSITION_SEEDS": post["MAPGEN_RELOAD_TRANSITION_SEEDS"],
        "MAPGEN_RELOAD_TRANSITION_SEED_COUNT": post["MAPGEN_RELOAD_TRANSITION_SEED_COUNT"],
        "MAPGEN_GENERATION_LINES": post["MAPGEN_GENERATION_LINES"],
        "MAPGEN_GENERATION_SEEDS": post["MAPGEN_GENERATION_SEEDS"],
        "MAPGEN_GENERATION_SEED_COUNT": post["MAPGEN_GENERATION_SEED_COUNT"],
        "MAPGEN_GENERATION_UNIQUE_SEED_COUNT": post["MAPGEN_GENERATION_UNIQUE_SEED_COUNT"],
        "MAPGEN_RELOAD_SEED_MATCH_COUNT": post["MAPGEN_RELOAD_SEED_MATCH_COUNT"],
        "MAPGEN_RELOAD_REGEN_OK": mapgen_reload_regen_ok,
        "TRACE_ACCOUNT_LABELS": ns.trace_account_labels,
        "REQUIRE_ACCOUNT_LABELS": ns.require_account_labels,
        "ACCOUNT_LABEL_LINES": optional["account_label_lines"],
        "ACCOUNT_LABEL_SLOTS": optional["account_label_slots"],
        "ACCOUNT_LABEL_MISSING_SLOTS": optional["account_label_missing_slots"],
        "ACCOUNT_LABEL_SLOT_COVERAGE_OK": optional["account_label_slot_coverage_ok"],
        "AUTO_KICK_TARGET_SLOT": ns.auto_kick_target_slot,
        "AUTO_KICK_DELAY_SECS": ns.auto_kick_delay,
        "REQUIRE_AUTO_KICK": ns.require_auto_kick,
        "AUTO_KICK_RESULT": optional["auto_kick_result"],
        "AUTO_KICK_OK_LINES": optional["auto_kick_ok_lines"],
        "AUTO_KICK_FAIL_LINES": optional["auto_kick_fail_lines"],
        "TRACE_SLOT_LOCKS": ns.trace_slot_locks,
        "REQUIRE_DEFAULT_SLOT_LOCKS": ns.require_default_slot_locks,
        "SLOT_LOCK_SNAPSHOT_LINES": optional["slot_lock_snapshot_lines"],
        "DEFAULT_SLOT_LOCK_OK": optional["default_slot_lock_ok"],
        "AUTO_PLAYER_COUNT_TARGET": ns.auto_player_count_target,
        "AUTO_PLAYER_COUNT_DELAY_SECS": ns.auto_player_count_delay,
        "TRACE_PLAYER_COUNT_COPY": ns.trace_player_count_copy,
        "REQUIRE_PLAYER_COUNT_COPY": ns.require_player_count_copy,
        "EXPECT_PLAYER_COUNT_COPY_VARIANT": ns.expect_player_count_copy_variant,
        "PLAYER_COUNT_PROMPT_LINES": optional["player_count_prompt_lines"],
        "PLAYER_COUNT_PROMPT_VARIANTS": optional["player_count_prompt_variants"],
        "PLAYER_COUNT_PROMPT_TARGET": optional["player_count_prompt_target"],
        "PLAYER_COUNT_PROMPT_KICKED": optional["player_count_prompt_kicked"],
        "PLAYER_COUNT_PROMPT_VARIANT": optional["player_count_prompt_variant"],
        "PLAYER_COUNT_COPY_OK": optional["player_count_copy_ok"],
        "TRACE_LOBBY_PAGE_STATE": ns.trace_lobby_page_state,
        "REQUIRE_LOBBY_PAGE_STATE": ns.require_lobby_page_state,
        "REQUIRE_LOBBY_PAGE_FOCUS_MATCH": ns.require_lobby_page_focus_match,
        "AUTO_LOBBY_PAGE_SWEEP": ns.auto_lobby_page_sweep,
        "AUTO_LOBBY_PAGE_DELAY_SECS": ns.auto_lobby_page_delay,
        "REQUIRE_LOBBY_PAGE_SWEEP": ns.require_lobby_page_sweep,
        "LOBBY_PAGE_SNAPSHOT_LINES": optional["lobby_page_snapshot_lines"],
        "LOBBY_PAGE_UNIQUE_COUNT": optional["lobby_page_unique_count"],
        "LOBBY_PAGE_TOTAL_COUNT": optional["lobby_page_total_count"],
        "LOBBY_PAGE_VISITED": optional["lobby_page_visited"],
        "LOBBY_FOCUS_MISMATCH_LINES": optional["lobby_focus_mismatch_lines"],
        "LOBBY_CARDS_MISALIGNED_MAX": optional["lobby_cards_misaligned_max"],
        "LOBBY_PAPERDOLLS_MISALIGNED_MAX": optional["lobby_paperdolls_misaligned_max"],
        "LOBBY_PINGS_MISALIGNED_MAX": optional["lobby_pings_misaligned_max"],
        "LOBBY_WARNINGS_PRESENT_LINES": optional["lobby_warnings_present_lines"],
        "LOBBY_WARNINGS_MAX_ABS_DELTA": optional["lobby_warnings_max_abs_delta"],
        "LOBBY_COUNTDOWN_PRESENT_LINES": optional["lobby_countdown_present_lines"],
        "LOBBY_COUNTDOWN_MAX_ABS_DELTA": optional["lobby_countdown_max_abs_delta"],
        "LOBBY_PAGE_STATE_OK": optional["lobby_page_state_ok"],
        "LOBBY_PAGE_SWEEP_OK": optional["lobby_page_sweep_ok"],
        "TRACE_REMOTE_COMBAT_SLOT_BOUNDS": ns.trace_remote_combat_slot_bounds,
        "REQUIRE_REMOTE_COMBAT_SLOT_BOUNDS": ns.require_remote_combat_slot_bounds,
        "REQUIRE_REMOTE_COMBAT_EVENTS": ns.require_remote_combat_events,
        "AUTO_PAUSE_PULSES": ns.auto_pause_pulses,
        "AUTO_PAUSE_DELAY_SECS": ns.auto_pause_delay,
        "AUTO_PAUSE_HOLD_SECS": ns.auto_pause_hold,
        "AUTO_REMOTE_COMBAT_PULSES": ns.auto_remote_combat_pulses,
        "AUTO_REMOTE_COMBAT_DELAY_SECS": ns.auto_remote_combat_delay,
        "REMOTE_COMBAT_SLOT_OK_LINES": optional["remote_combat_slot_ok_lines"],
        "REMOTE_COMBAT_SLOT_FAIL_LINES": optional["remote_combat_slot_fail_lines"],
        "REMOTE_COMBAT_EVENT_LINES": optional["remote_combat_event_lines"],
        "REMOTE_COMBAT_EVENT_CONTEXTS": optional["remote_combat_event_contexts"],
        "REMOTE_COMBAT_AUTO_PAUSE_ACTION_LINES": optional["remote_combat_pause_action_lines"],
        "REMOTE_COMBAT_AUTO_PAUSE_COMPLETE_LINES": optional["remote_combat_pause_complete_lines"],
        "REMOTE_COMBAT_AUTO_ENEMY_BAR_LINES": optional["remote_combat_enemy_bar_action_lines"],
        "REMOTE_COMBAT_AUTO_ENEMY_COMPLETE_LINES": optional["remote_combat_enemy_complete_lines"],
        "REMOTE_COMBAT_SLOT_BOUNDS_OK": optional["remote_combat_slot_bounds_ok"],
        "REMOTE_COMBAT_EVENTS_OK": optional["remote_combat_events_ok"],
        "HOST_LOG": host_log,
        "PID_FILE": pid_file,
    }
